console.log('start');
var name = prompt("Please enter your first name:");
var noun = prompt("Please enter a Noun:");
var adjective = prompt("Please enter an Adjective:");
var verb = prompt("Please enter a Verb:");
var outPut = "John took an " + adjective + ", ";
outPut += "stubborn " + noun; 
outPut += " for a " + verb + "."; 
alert("Are you ready to see the story?");
document.write(outPut);
console.log(outPut);
console.log('end');